- name: Play level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

# If we declare a variable on play level then all the tasks can access that variable

- name: Play level variables from a file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Task level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: hosts.example.com


# If we declare a variable on tasks level then only that tasks can access that variable

- name: Inventory variable
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Fact variable
  hosts: all
  tasks:
    - name: Print Hostname
      ansible.builtin.debug:
        msg: Architecture = {{ansible_architecture}}, IP address = {{ansible_eth0.ipv4.address}}


- name: Register variable
  hosts: all
  tasks:
    - name : Run a shell command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Set a fact
      ansible.builtin.set_fact:
        OUTPUT: "{{OUT.stdout}}"

    - name: Print Output of shell command
      ansible.builtin.debug:
        msg: "{{OUTPUT}}"






